// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNunitWeb.Data;

#nullable disable

namespace MyNunitWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221025190243_AddTestResultsToDb")]
    partial class AddTestResultsToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyNunitWeb.Models.AssemblyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestAssmblies");
                });

            modelBuilder.Entity("MyNunitWeb.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AssemblyModelId")
                        .HasColumnType("int");

                    b.Property<long>("ExecutionTime")
                        .HasColumnType("bigint");

                    b.Property<string>("IgnoreReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyModelId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("MyNunitWeb.Models.TestModel", b =>
                {
                    b.HasOne("MyNunitWeb.Models.AssemblyModel", null)
                        .WithMany("tests")
                        .HasForeignKey("AssemblyModelId");
                });

            modelBuilder.Entity("MyNunitWeb.Models.AssemblyModel", b =>
                {
                    b.Navigation("tests");
                });
#pragma warning restore 612, 618
        }
    }
}
